import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Brand tokens from Stitch design system
        "primary": "#003527",
        "primary-container": "#064e3b",
        "primary-fixed": "#b0f0d6",
        "primary-fixed-dim": "#95d3ba",
        "on-primary": "#ffffff",
        "on-primary-container": "#80bea6",
        "on-primary-fixed": "#002117",
        "on-primary-fixed-variant": "#0b513d",
        "secondary": "#4c6359",
        "secondary-container": "#cce6d9",
        "secondary-fixed": "#cfe8dc",
        "secondary-fixed-dim": "#b3ccc0",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#50685d",
        "on-secondary-fixed": "#091f18",
        "on-secondary-fixed-variant": "#354b42",
        "tertiary": "#4f1f19",
        "tertiary-container": "#6b342d",
        "tertiary-fixed": "#ffdad5",
        "tertiary-fixed-dim": "#ffb4a9",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ea9e93",
        "on-tertiary-fixed": "#380d08",
        "on-tertiary-fixed-variant": "#6e372f",
        "background": "#f7f9fb",
        "surface": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "surface-bright": "#f7f9fb",
        "surface-tint": "#2b6954",
        "surface-variant": "#e0e3e5",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "on-surface": "#191c1e",
        "on-surface-variant": "#404944",
        "on-background": "#191c1e",
        "outline": "#707974",
        "outline-variant": "#bfc9c3",
        "inverse-primary": "#95d3ba",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "1.5rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["var(--font-inter)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"],
      },
      keyframes: {
        "float": {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-8px)" },
        },
        "fade-up": {
          "0%": { opacity: "0", transform: "translateY(24px) scale(0.98)" },
          "100%": { opacity: "1", transform: "translateY(0) scale(1)" },
        },
        "slide-in-right": {
          "0%": { opacity: "0", transform: "translateX(24px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        "shake": {
          "0%, 100%": { transform: "translateX(0)" },
          "25%": { transform: "translateX(-6px)" },
          "75%": { transform: "translateX(6px)" },
        },
        "scale-check": {
          "0%": { transform: "scale(0)", opacity: "0" },
          "50%": { transform: "scale(1.2)" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
      },
      animation: {
        "float": "float 4s ease-in-out infinite",
        "fade-up": "fade-up 0.7s cubic-bezier(0.25, 1, 0.3, 1) forwards",
        "slide-in-right": "slide-in-right 0.5s cubic-bezier(0.25, 1, 0.3, 1) forwards",
        "shake": "shake 0.4s ease-in-out",
        "scale-check": "scale-check 0.5s cubic-bezier(0.34, 1.56, 0.64, 1) forwards",
        "fade-in": "fade-in 0.5s ease-out forwards",
      },
    },
  },
  plugins: [],
};

export default config;
